# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-cloudflare-zone
  description: Terraform module to provision a CloudFlare zone with DNS records, Argo, Firewall filters and rules
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-module, cloudflare



